// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWRHu7TOwaHT6fkm28n-sbf0wDnFkMjk',
    appId: '1:4717444796:web:7ce66390d49a275cc75ab9',
    messagingSenderId: '4717444796',
    projectId: 'healthcare-freelance',
    authDomain: 'healthcare-freelance.firebaseapp.com',
    databaseURL: 'https://healthcare-freelance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcare-freelance.appspot.com',
    measurementId: 'G-8YZS4S08RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJsQryRVZ-wXQ9K-Mnbh-kTQ4fmuSWG0',
    appId: '1:4717444796:android:34b5fd0551f0b9e4c75ab9',
    messagingSenderId: '4717444796',
    projectId: 'healthcare-freelance',
    databaseURL: 'https://healthcare-freelance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcare-freelance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPSVKgVOG5TaAe3ZuLz4ZA69-TSuCTq20',
    appId: '1:4717444796:ios:ef499d91feca2596c75ab9',
    messagingSenderId: '4717444796',
    projectId: 'healthcare-freelance',
    databaseURL: 'https://healthcare-freelance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcare-freelance.appspot.com',
    iosClientId: '4717444796-t2b3job5rocgljgker7cnpm3nhsh9fn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
